version: '2'
services:
  leafservice3-app:
    image: leafservice3
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://leafservice3-mysql:3306/leafservice3?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://leafservice3-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://leafservice3-elasticsearch:9200
    ports:
      - 8080:8080
  leafservice3-mysql:
    extends:
      file: mysql.yml
      service: leafservice3-mysql
  leafservice3-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: leafservice3-elasticsearch
